### ISSUE TITLE
Even with no sidebar content on latest nodebb; I get col-md-9

### ISSUE THREAD

**Issue by Icehunter** [NodeBB/nodebb-plugin-custom-homepage#24]
I upgraded to the latest nodebb and locally testing shows that I no longer have a fullscreen wide custom homepage and instead it's defaulting to the col-md-9 class.

I have no sidebar content registered for that page; is there something that I can change? Anything required for details?

Thanks!

**Comment by phit** [comment]
submitted a fix #25

**Comment by Jenkler** [comment]
Would be nice to get this patch merged ;)
