### ISSUE TITLE
Disabling global widgets on the homepage?

### ISSUE THREAD

**Issue by lukespragg** [NodeBB/nodebb-plugin-custom-homepage#8]
I've been attempting to do this, but so far my attempts are nil. I haven't dug into NodeBB much yet, so the workings are a bit unfamiliar to me right now. Is there any easy way to do this that wouldn't require modifying the core of NodeBB directly?

**Comment by julianlam** [comment]
Hi @lukespragg, you'll want to comment on our forum or open an issue on the main repository instead :smile:
